name: Auto Generate PR Description

on:
  workflow_call:
    inputs:
      repository_owner:
        required: true
        type: string
      repository_name:
        required: true
        type: string
      pull_request_number:
        required: true
        type: number
      branch_name:
        required: true
        type: string

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate PR description
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node generatePRDescription.js ${{ inputs.repository_owner }} ${{ inputs.repository_name }} ${{ inputs.pull_request_number }} ${{ inputs.branch_name }}
